# Generated by Django 2.1.7 on 2019-04-28 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaghaze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_meli', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=500)),
                ('postal_code', models.IntegerField(max_length=9)),
                ('phone_number', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
