# Generated by Django 2.1.7 on 2019-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_usermaghaze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaghaze',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='usermaghaze',
            name='postal_code',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usermoshtari',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='usermoshtari',
            name='postal_code',
            field=models.IntegerField(max_length=10),
        ),
    ]
