# Generated by Django 2.1.7 on 2019-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20190428_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaghaze',
            name='code_meli',
            field=models.IntegerField(max_length=50),
        ),
    ]
