# Generated by Django 2.1.7 on 2019-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20190428_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaghaze',
            name='code_meli',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermaghaze',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usermoshtari',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
